"use client"
import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import Link from 'next/link'
import { useRouter, useSearchParams } from 'next/navigation'
import { Code2, Github, Mail, Lock, User, GraduationCap, BookOpen, Eye, EyeOff, ArrowRight, Check, Sparkles, Shield, Zap, Brain, FlaskConical, BarChart3, ShieldCheck } from 'lucide-react'
import { useAuthStore } from '@/lib/store'
import { authApi } from '@/lib/api'
import toast from 'react-hot-toast'

const API = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:5000'

const strengthColors = ['#FF5A5F', '#FF9E00', '#FFD600', '#00C896']
const strengthLabels = ['Weak', 'Fair', 'Good', 'Strong']

function getPasswordStrength(pwd) {
  let score = 0
  if (pwd.length >= 6) score++
  if (pwd.length >= 10) score++
  if (/[A-Z]/.test(pwd) && /[0-9]/.test(pwd)) score++
  if (/[^A-Za-z0-9]/.test(pwd)) score++
  return Math.min(score, 3)
}

const features = [
  {
    icon: Brain,
    color: '#00B4D8',
    bg: 'rgba(0,180,216,0.1)',
    title: 'AI-Powered Grading',
    desc: 'Get instant, detailed feedback and hints generated by advanced AI models.',
  },
  {
    icon: FlaskConical,
    color: '#00C896',
    bg: 'rgba(0,200,150,0.1)',
    title: 'Safe Code Execution',
    desc: 'Run code in isolated sandboxes supporting 10+ programming languages.',
  },
  {
    icon: ShieldCheck,
    color: '#a78bfa',
    bg: 'rgba(167,139,250,0.1)',
    title: 'Plagiarism Detection',
    desc: 'Advanced similarity analysis to ensure academic integrity across all submissions.',
  },
  {
    icon: BarChart3,
    color: '#fbbf24',
    bg: 'rgba(251,191,36,0.1)',
    title: 'Live Leaderboards',
    desc: 'Real-time rankings, XP progression, and competitive contest scoring.',
  },
]

const testimonial = {
  quote: "AutoJudge is the only platform where I get honest AI feedback within seconds. My rating went from 1200 to 1850 in 3 months.",
  name: 'Priya Sharma',
  role: 'ICPC Regional Finalist',
  avatar: 'PS',
}

export default function RegisterPage() {
  const params = useSearchParams()
  const [form, setForm] = useState({ name: '', email: '', password: '', role: params.get('role') || 'student' })
  const [showPwd, setShowPwd] = useState(false)
  const [loading, setLoading] = useState(false)
  const [focused, setFocused] = useState({})
  const [agreed, setAgreed] = useState(false)
  const { login } = useAuthStore()
  const router = useRouter()

  const pwdStrength = getPasswordStrength(form.password)

  const handleSubmit = async (e) => {
    e.preventDefault()
    if (!agreed) return toast.error('Please accept the terms to continue')
    setLoading(true)
    try {
      const { data } = await authApi.register(form)
      login(data.user, data.accessToken)
      toast.success('Account created! Welcome to AutoJudge 🎉')
      router.push(data.user.role === 'teacher' ? '/teacher/dashboard' : '/student/dashboard')
    } catch (err) {
      toast.error(err.response?.data?.message || 'Registration failed')
    } finally { setLoading(false) }
  }

  const fields = [
    { name: 'name', icon: User, label: 'Full Name', type: 'text', placeholder: 'Aarya Kale' },
    { name: 'email', icon: Mail, label: 'Email Address', type: 'email', placeholder: 'aaryakale0607@example.com' },
  ]

  return (
    <div className="min-h-screen auth-split-bg flex overflow-hidden">
      {/* ── LEFT PANEL — Form ───────────────────────────────── */}
      <div className="w-full lg:w-[52%] flex items-center justify-center px-6 py-10 relative overflow-y-auto order-2 lg:order-1">
        <div className="absolute inset-0 lg:hidden auth-right-mobile-bg" />
        <div className="absolute inset-0 auth-left-grid opacity-[0.05]" />
        <motion.div initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: 0.55, ease: [0.22,1,0.36,1] }}
          className="w-full max-w-[460px] relative z-10">

          {/* Mobile logo */}
          <div className="flex lg:hidden justify-center mb-7">
            <Link href="/" className="inline-flex items-center gap-3">
              <div className="auth-logo"><Code2 className="w-5 h-5 text-white" /></div>
              <span className="font-black text-2xl">Auto<span className="gradient-text">Judge</span></span>
            </Link>
          </div>

          <div className="auth-glass-card">

          <div className="mb-6">
            <motion.h1 initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}
              className="text-3xl font-black tracking-tight mb-2 leading-tight">
              Create <span className="gradient-text">account</span>
            </motion.h1>
            <motion.p initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.2 }}
              className="text-gray-500 text-sm">Join thousands of coders today</motion.p>
          </div>

          {/* Role selector */}
          <div className="grid grid-cols-2 gap-3 mb-6">
            {[
              { r: 'student', icon: GraduationCap, label: 'Student', sub: 'Practice & compete' },
              { r: 'teacher', icon: BookOpen, label: 'Teacher', sub: 'Create & grade' },
            ].map(({ r, icon: Icon, label, sub }) => (
              <motion.button key={r} type="button" onClick={() => setForm(p => ({ ...p, role: r }))}
                whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.97 }}
                className={`auth-role-btn-v2 ${form.role === r ? 'active' : ''}`}>
                <div className={`w-10 h-10 rounded-xl flex items-center justify-center mb-2 transition-colors ${form.role === r ? 'bg-cyan-400/20 border border-cyan-400/30' : 'bg-white/[0.08] border border-white/[0.08]'}`}>
                  <Icon className={`w-5 h-5 transition-colors ${form.role === r ? 'text-cyan-400' : 'text-gray-400'}`} />
                </div>
                <span className={`font-bold text-sm block ${form.role === r ? 'text-cyan-300' : 'text-gray-300'}`}>{label}</span>
                <span className="text-xs text-gray-600 mt-0.5">{sub}</span>
                {form.role === r && (
                  <motion.div layoutId="role-ring"
                    className="absolute inset-0 rounded-[14px] border-2 border-cyan-400/50 pointer-events-none"
                    transition={{ type: 'spring', stiffness: 400, damping: 28 }} />
                )}
              </motion.button>
            ))}
          </div>

          {/* OAuth */}
          <div className="grid grid-cols-2 gap-3 mb-5">
            <motion.a whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.97 }}
              href={`${API}/api/auth/google`} className="auth-oauth-btn-v2">
              <svg className="w-4 h-4" viewBox="0 0 24 24">
                <path fill="#4285F4" d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z"/>
                <path fill="#34A853" d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"/>
                <path fill="#FBBC05" d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z"/>
                <path fill="#EA4335" d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z"/>
              </svg>
              Google
            </motion.a>
            <motion.a whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.97 }}
              href={`${API}/api/auth/github`} className="auth-oauth-btn-v2">
              <Github className="w-4 h-4" /> GitHub
            </motion.a>
          </div>

          <div className="auth-divider mb-5"><span>or with email</span></div>

          <form onSubmit={handleSubmit} className="space-y-4">

            {/* Name & Email */}
            {fields.map(({ name, icon: Icon, label, type, placeholder }) => (
              <div key={name}>
                <label className="auth-label mb-2 block">{label}</label>
                <div className="relative">
                  <Icon className={`auth-field-icon transition-colors ${focused[name] ? 'text-cyan-400' : 'text-gray-600'}`} />
                  <input type={type} required placeholder={placeholder}
                    className={`auth-input-v2 pl-10 pr-10 ${focused[name] ? 'focused' : ''}`}
                    value={form[name]}
                    onFocus={() => setFocused(p => ({ ...p, [name]: true }))}
                    onBlur={() => setFocused(p => ({ ...p, [name]: false }))}
                    onChange={e => setForm(p => ({ ...p, [name]: e.target.value }))} />
                  <AnimatePresence>
                    {form[name].length > 0 && (
                      <motion.div initial={{ scale: 0, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} exit={{ scale: 0, opacity: 0 }}
                        className="absolute right-3 top-1/2 -translate-y-1/2 w-5 h-5 rounded-full bg-green-500/15 border border-green-500/30 flex items-center justify-center">
                        <Check className="w-3 h-3 text-green-400" />
                      </motion.div>
                    )}
                  </AnimatePresence>
                </div>
              </div>
            ))}

            {/* Password */}
            <div>
              <label className="auth-label mb-2 block">Password</label>
              <div className="relative">
                <Lock className={`auth-field-icon transition-colors ${focused.password ? 'text-cyan-400' : 'text-gray-600'}`} />
                <input type={showPwd ? 'text' : 'password'} required placeholder="Min 6 characters"
                  className={`auth-input-v2 pl-10 pr-10 ${focused.password ? 'focused' : ''}`}
                  value={form.password}
                  onFocus={() => setFocused(p => ({ ...p, password: true }))}
                  onBlur={() => setFocused(p => ({ ...p, password: false }))}
                  onChange={e => setForm(p => ({ ...p, password: e.target.value }))} />
                <button type="button" onClick={() => setShowPwd(!showPwd)}
                  className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-600 hover:text-cyan-400 transition-colors">
                  {showPwd ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                </button>
              </div>

              <AnimatePresence>
                {form.password.length > 0 && (
                  <motion.div initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: 'auto' }} exit={{ opacity: 0, height: 0 }}
                    className="mt-2.5 overflow-hidden">
                    <div className="flex gap-1.5 mb-1.5">
                      {[0,1,2,3].map(i => (
                        <div key={i} className="auth-strength-bar">
                          <motion.div className="auth-strength-fill"
                            animate={{ width: i <= pwdStrength ? '100%' : '0%', background: strengthColors[pwdStrength] }}
                            transition={{ duration: 0.3, delay: i * 0.04 }} />
                        </div>
                      ))}
                    </div>
                    <p className="text-xs font-semibold" style={{ color: strengthColors[pwdStrength] }}>
                      {strengthLabels[pwdStrength]} password
                    </p>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>

            {/* Terms */}
            <label className="flex items-start gap-3 cursor-pointer">
              <motion.div
                whileTap={{ scale: 0.9 }}
                onClick={() => setAgreed(!agreed)}
                className={`w-5 h-5 rounded-md border-2 flex items-center justify-center shrink-0 mt-0.5 transition-all ${agreed ? 'bg-cyan-400 border-cyan-400' : 'border-white/20 hover:border-cyan-400/50'}`}>
                <AnimatePresence>
                  {agreed && (
                    <motion.div initial={{ scale: 0 }} animate={{ scale: 1 }} exit={{ scale: 0 }}>
                      <Check className="w-3 h-3 text-[#040d1a]" />
                    </motion.div>
                  )}
                </AnimatePresence>
              </motion.div>
              <span className="text-sm text-gray-500 leading-relaxed">
                I agree to the{' '}
                <a href="#" className="text-cyan-400 hover:text-cyan-300 transition-colors">Terms of Service</a>{' '}and{' '}
                <a href="#" className="text-cyan-400 hover:text-cyan-300 transition-colors">Privacy Policy</a>
              </span>
            </label>

            <motion.button type="submit" disabled={loading}
              whileHover={{ scale: loading ? 1 : 1.01 }} whileTap={{ scale: loading ? 1 : 0.98 }}
              className="auth-submit-btn-v2 w-full mt-1">
              {loading ? (
                <span className="flex items-center justify-center gap-2">
                  <svg className="animate-spin w-4 h-4" viewBox="0 0 24 24" fill="none">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/>
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/>
                  </svg>
                  Creating account...
                </span>
              ) : (
                <span className="flex items-center justify-center gap-2">
                  Create {form.role === 'teacher' ? 'Teacher' : 'Student'} Account <ArrowRight className="w-4 h-4" />
                </span>
              )}
            </motion.button>
          </form>

          <p className="text-center text-sm text-gray-500 mt-5">
            Already have an account?{' '}
            <Link href="/auth/login" className="text-cyan-400 hover:text-cyan-300 font-bold transition-colors">
              Sign in →
            </Link>
          </p>

          </div>{/* end auth-glass-card */}

          <div className="flex justify-center gap-5 mt-5">
            {[['🎯', 'Free Forever'], ['💳', 'No Credit Card'], ['✨', 'AI-Powered']].map(([icon, label], i) => (
              <span key={i} className="text-xs text-gray-700 flex items-center gap-1 font-medium">{icon} {label}</span>
            ))}
          </div>
        </motion.div>
      </div>

      {/* ── RIGHT PANEL — Feature Showcase ─────────────────── */}
      <div className="hidden lg:flex lg:w-[48%] relative flex-col justify-between p-14 auth-left-panel overflow-hidden order-1 lg:order-2">

        <div className="absolute inset-0 auth-left-grid" />
        <motion.div className="absolute -top-24 -left-24 w-[440px] h-[440px] rounded-full pointer-events-none"
          style={{ background: 'radial-gradient(circle, rgba(0,200,150,0.12) 0%, transparent 65%)' }}
          animate={{ scale: [1, 1.16, 1] }} transition={{ duration: 9, repeat: Infinity, ease: 'easeInOut' }} />
        <motion.div className="absolute -bottom-24 right-0 w-80 h-80 rounded-full pointer-events-none"
          style={{ background: 'radial-gradient(circle, rgba(0,180,216,0.1) 0%, transparent 65%)' }}
          animate={{ scale: [1, 1.2, 1] }} transition={{ duration: 7, repeat: Infinity, delay: 2, ease: 'easeInOut' }} />

        {/* Branding */}
        <motion.div initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }} className="relative z-10">
          <Link href="/" className="inline-flex items-center gap-3">
            <div className="auth-logo-xl">
              <Code2 className="w-7 h-7 text-white" />
            </div>
            <div>
              <span className="font-black text-3xl tracking-tight">Auto<span className="gradient-text">Judge</span></span>
              <p className="text-xs text-gray-500 font-medium tracking-widest uppercase mt-0.5">Competitive Programming</p>
            </div>
          </Link>
          <p className="text-gray-400 mt-4 text-sm leading-7 max-w-sm">
            Everything you need to <span className="text-cyan-400 font-semibold">practice, compete, and grow</span> as a programmer — all in one platform.
          </p>
        </motion.div>

        {/* Feature cards */}
        <div className="relative z-10 space-y-3">
          {features.map(({ icon: Icon, color, bg, title, desc }, i) => (
            <motion.div key={i}
              initial={{ opacity: 0, x: 30 }} animate={{ opacity: 1, x: 0 }}
              transition={{ delay: 0.2 + i * 0.1, duration: 0.5 }}
              className="auth-feature-card">
              <div className="w-10 h-10 rounded-xl flex items-center justify-center shrink-0" style={{ background: bg }}>
                <Icon className="w-5 h-5" style={{ color }} />
              </div>
              <div>
                <p className="font-bold text-sm text-white mb-0.5">{title}</p>
                <p className="text-xs text-gray-500 leading-relaxed">{desc}</p>
              </div>
            </motion.div>
          ))}
        </div>

        {/* Testimonial */}
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.7 }}
          className="relative z-10 bg-white/[0.03] border border-white/[0.07] rounded-xl p-5">
          <div className="flex gap-1 mb-3">
            {[...Array(5)].map((_, i) => (
              <svg key={i} className="w-3.5 h-3.5 text-yellow-400 fill-yellow-400" viewBox="0 0 20 20">
                <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"/>
              </svg>
            ))}
          </div>
          <p className="text-gray-300 text-sm leading-relaxed italic mb-4">&ldquo;{testimonial.quote}&rdquo;</p>
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-full bg-gradient-to-br from-cyan-400 to-emerald-400 flex items-center justify-center text-xs font-black text-[#040d1a]">
              {testimonial.avatar}
            </div>
            <div>
              <p className="text-sm font-bold text-white">{testimonial.name}</p>
              <p className="text-xs text-gray-500">{testimonial.role}</p>
            </div>
          </div>
        </motion.div>
      </div>
    </div>
  )
}
